$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

experiment_name: llma2-fine-tuning
description: llma2-fine-tuning
jobs:
  train:
    type: command
    code: ./
    command: >-
      accelerate launch  --config_file launch.yml main.py
      --model_dir ${{inputs.model_dir}}
      --epochs ${{inputs.epochs}}
      --trained_model ${{outputs.output_dir}}
    inputs:
      epochs: 1
      model_dir: 
        path: azureml://registries/azureml-meta/models/Llama-2-13b/versions/5
    environment: 
      conda_file: ./conda.yml
      image: mcr.microsoft.com/azureml/curated/acft-hf-nlp-gpu
    outputs:
      output_dir:
        type: uri_folder
        path: azureml://datastores/workspaceblobstore/paths/azureml/
    compute: azureml:NC48adsA100

    # distribution:
    #   type: pytorch
    #   process_count_per_instance: 1
    # resources:
    #   instance_count: 2
